export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIE = "FETCH_MOVIE";
export const GET_USERNAME = "GET_USERNAME";
export const ADD_FAVORITE_MOVIE = "ADD_FAVORITE_MOVIE";
export const DETAIL_MOVIE = "DETAIL_MOVIE";
